WIP: fix(`PromiseReleaseReconciler`): Fail if installing Promise fails
syntasso/kratix pull request #101
Opened 2024-03-30 21:02 UTC by Bhargav-InfraCloud

Fail the `PromiseReleaseReconciler` if there is an error installing the referenced promise.

Add an event to PromiseRelease to state the reason for the failure of installing Promise. If it fails because of an invalid Promise manifest referenced, state the reason in the event accordingly.

Add RBAC permissions to `PromiseReleaseReconciler` to `CREATE` and `PATCH` `events` on itself in-cluster.

Fixes #87

2024-04-08 06:57 UTC, Bhargav-InfraCloud commented
CC: kirederik

2024-04-15 08:47 UTC, kirederik requested changes

2024-04-21 14:41 UTC, Bhargav-InfraCloud commented on controllers/promiserelease_controller_test.go
> +						)
Ah! Didn't realize there's a func in Gomega for the same. Thanks! I updated it.

2024-04-21 14:42 UTC, Bhargav-InfraCloud commented on controllers/promiserelease_controller_test.go
> +	// This test is separated from the original nested tests in order to test using mocked kubeclient's method(s)
You are right. Overwriting it should do. Done. Thanks!

2024-04-24 15:01 UTC, kirederik approved these changes
good stuff! Thanks!

We'll sort the CLA and get this one merged soon!

2024-05-08 14:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/syntasso/kratix?pullRequest=101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/syntasso/kratix?pullRequest=101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/syntasso/kratix?pullRequest=101) it.</sub>

2024-05-08 14:41 UTC, Bhargav-InfraCloud commented
Signed the CLA. Thanks!

2024-05-08 15:05 UTC, kirederik commented
Awesome! Thanks @Bhargav-InfraCloud and thanks for your patience.

2024-05-08 15:30 UTC, merged

2024-05-08 15:53 UTC, Bhargav-InfraCloud commented
Thanks @kirederik! 😊